[package]
name = "postnl"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[lib]
name = "postnl"
path = "src/lib.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[dependencies]
reqwest = { version = "0.9", features = ["rustls"] }
maplit = "1.0"
serde = { version = "1.0", features = ["derive"] }
parse-display = "0.1"
chrono = { version = "0.4", features = ["serde"] }
iso_country = { version = "0.1", features = ["serde"] }
dotenv = "0.14"